# Database URL (Neon PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-ancient-bird-aodow8ap-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Xsue9QmU4ZRK

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

# JWT Configuration (In production, use a strong 256-bit environment variable)
jwt.secret=YzhhNWVkMTcwNjdiZjhiODhhMDY3MWE2MDMzNDUyMTk5YzlmNjA2NjVkODhmMzIyNTkyNzZiMjQwNDBkNGJmZQ==
jwt.expirationMs=86400000